apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cr9kkadhl-python-development
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/cr9kkadhl-python/overlays/development
    repoURL: https://github.com/rhtap-rhdh-qe/cr9kkadhl-python-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
